databases:
  - name: appsforceyk
    plan: free
    databaseName: appsforceyk
    user: appsforceuser

services:
  - type: web
    plan: free
    name: appsforceyk
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn appsforceyk.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: appsforceyk
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
