# Generated by Django 5.0.3 on 2024-04-02 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(2, 'Department name must contain at least 2 characters')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(2, 'first name must contain at least 2 characters')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(2, 'last name must contain at least 2 characters')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True),
        ),
    ]
